### ISSUE TITLE
Can't scan QR code with a dark theme enabled

### ISSUE THREAD

**Issue by tetov** [sn-extensions/mfa-link#8] opened 2020-06-04 18:13 UTC
Neither 1Password's Windows client, 1Password's iOS client or iOS built in QR scanner would recognize the QR code as a QR code when I had [midnight](https://github.com/sn-extensions/midnight-theme) enabled.

There seems to be grey/white lines separating the qr code into 9 grid cells that are only visible if the background is dark. I'm not posting a screenshot because I'm not sure that's safe.

**Comment by JaspalSuri** [comment] 2020-06-05 08:03
Thanks so much for this report! I was able to reproduce this on my end in web app while using Authy. It doesn't work with the Focus theme either, so it's definitely an issue with dark themes.

While I can't say it's safe to share a screenshot, QR code and text-based code change each time (in different ways, depending upon the service). 

I forward this for internal review. Thanks again!

**Comment by tetov** [comment] 2020-06-05 08:20
Super that you could reproduce it!

Maybe try getting SVG from https://github.com/zpao/qrcode.react instead? Sorry not very good at JS so can't submit a PR here.

**Comment by JaspalSuri** [comment] 2020-06-05 08:26
No worries! I am personally not sure but I appreciate your contribution and whoever reads this thread will be happy to consider it. It could as simple as putting a slightly larger white square behind the image, I think.

**Comment by JaspalSuri** [comment] 2021-04-02 09:07
Hi @tetov,

I am closing this thread since I am unable to reproduce this issue when using different dark themes (including Midnight and Focus). I've used 1Password, Google Authenticator, and Authy in my tests and have not run into any issues. Thanks again for having brought this to our attention. 🙂

**Closed as completed by JaspalSuri** 2021-04-02 09:07 UTC

**Comment by JaspalSuri** [comment] 2021-05-29 11:15
Hi @tetov, I was able to reproduce this issue on Android after receiving another report, but the issue will be resolved soon as a white border will be added to the QR code. Thank you again for taking the time to report this issue!
